In [164]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [165]:
N = 1000

In [166]:
X = np.random.normal(0.25,1,N)

In [167]:
X

array([-0.80286363,  0.67642048,  1.38412871,  0.55059565, -1.1145241 ,
        0.03749246,  1.19497055, -0.32667202,  0.07047896,  2.50824185,
        1.98122789,  1.32763293,  0.7458135 ,  0.49767764,  0.38953418,
        0.49138522, -0.92409765, -0.81523388, -0.86303418,  1.1512559 ,
       -0.06410289,  0.7707699 , -0.13588008,  1.95071217,  1.16876727,
        1.65961462,  1.77023374,  1.07739318,  0.7408698 , -0.51327831,
       -0.12433418,  1.34503682,  0.05331647, -0.71876287,  0.290211  ,
        1.29252596, -1.1030508 ,  1.51891682,  0.45307288,  0.37790801,
        0.43803106,  0.43851302,  1.59156336, -0.02186204, -0.47373801,
        0.5392914 ,  0.69684274, -1.05295268,  1.94450214, -0.07092271,
        1.83122621, -1.10702101, -1.08059801,  0.79658579,  0.17819065,
       -0.7529518 ,  0.11482772,  0.64082166, -1.07496478,  0.05947919,
        1.21183436, -1.02982241, -0.55974023,  1.36402705, -0.03637265,
        0.18041276, -0.1216959 ,  0.14174233,  0.5006849 ,  0.80

In [168]:
X.mean()


0.2282961643695636

In [169]:
X.std()

0.9687405190425904

In [170]:
1/np.sqrt(len(X))

0.03162277660168379

In [171]:
Z = np.random.choice(X,3)

In [172]:
Z


array([-0.899972  ,  0.99651884, -0.8272283 ])

In [173]:
MC = 100000
vset = []
vset2 = []
for m in np.arange(MC):
    Z = np.random.choice(X,len(X))
    vset.append(Z.mean()) 
    vset2.append(Z.var())
vset = np.array(vset)  
vset2 = np.array(vset2)

In [174]:
vset

array([0.24896775, 0.23190228, 0.20824328, ..., 0.23205364, 0.22133798,
       0.21778236])

In [175]:
vm = vset.mean()
vm2 = vset2.mean()

In [176]:
SE = np.sqrt(np.dot(vset-vm,vset-vm)/(MC-1))
SE2 = np.sqrt(np.dot(vset2-vm2,vset2-vm2)/(MC-1))

In [180]:
1/np.sqrt(len(X))

0.03162277660168379

In [177]:
SE

0.030688760364635876

In [178]:
np.sqrt(2)*pow(1,2)/np.sqrt(len(X))

0.0447213595499958

In [179]:
SE2

0.0410829942935717